/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}", "./utils/**/*.{js,ts,jsx,tsx}"],
  plugins: [require("daisyui")],
  darkTheme: "dark",
  darkMode: ["selector", "[data-theme='dark']"],
  daisyui: {
    themes: [
      {
        light: {
          primary: "#836EF9",
          "primary-content": "#0E100F",
          secondary: "#A0055D",
          "secondary-content": "#FBFAF9",
          accent: "#200052",
          "accent-content": "#FBFAF9",
          neutral: "#0E100F",
          "neutral-content": "#FFFFFF",
          "base-100": "#FBFAF9",
          "base-200": "#F4F4F3",
          "base-300": "#EAEAE9",
          "base-content": "#0E100F",
          info: "#836EF9",
          success: "#34EEB6",
          warning: "#FFCF72",
          error: "#FF8863",
          "--rounded-btn": "9999rem",
          ".tooltip": { "--tooltip-tail": "6px" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
      {
        dark: {
          primary: "#836EF9",
          "primary-content": "#FBFAF9",
          secondary: "#A0055D",
          "secondary-content": "#FBFAF9",
          accent: "#200052",
          "accent-content": "#FBFAF9",
          neutral: "#FBFAF9",
          "neutral-content": "#0E100F",
          "base-100": "#200052",
          "base-200": "#1A0042",
          "base-300": "#0E100F",
          "base-content": "#FBFAF9",
          info: "#836EF9",
          success: "#34EEB6",
          warning: "#FFCF72",
          error: "#FF8863",
          "--rounded-btn": "9999rem",
          ".tooltip": { "--tooltip-tail": "6px", "--tooltip-color": "oklch(var(--p))" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
    ],
  },
  theme: {
    extend: {
      colors: {
        monad: {
          offwhite: "#FBFAF9",
          purple: "#836EF9",
          blue: "#200052",
          berry: "#A0055D",
          black: "#0E100F",
        },
      },
      boxShadow: { center: "0 0 12px -2px rgb(0 0 0 / 0.05)" },
      animation: { "pulse-fast": "pulse 1s cubic-bezier(0.4, 0, 0.6, 1) infinite" },
    },
  },
};
